[package]
name = "nc-daemon"
description = "Daemon logic of nextcloud-client-rs (unofficial port of the Nextcloud desktop client folder manager, folder watcher and account state)"
license = "GPL-2.0-or-later"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
nc-journal.workspace = true
nc-dav.workspace = true
nc-sync.workspace = true
log.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["net", "signal"] }
tokio-util.workspace = true
serde_json.workspace = true
inotify.workspace = true
regex.workspace = true
serde.workspace = true
http.workspace = true
fastrand.workspace = true
rustix.workspace = true
sd-notify = "0.5.0"

[dev-dependencies]
tempfile.workspace = true
nc-testutils.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
